CREATE TABLE IF NOT EXISTS DEPARTMENT 
(
  DPT_ID INTEGER AUTO_INCREMENT,
  NAME VARCHAR(20) NOT NULL,
  DESCRIPTION VARCHAR(50) NULL,
  PRIMARY KEY (DPT_ID)
);

CREATE TABLE IF NOT EXISTS EMPLOYEE
(
  EMP_ID INTEGER AUTO_INCREMENT,
  NAME VARCHAR(20) NOT NULL ,
  DPT_ID INTEGER NOT NULL ,
  GENDER VARCHAR(1) NOT NULL ,
  PHONE VARCHAR(20) NOT NULL ,
  ADDRESS VARCHAR(100) NOT NULL ,
  AGE INTEGER NOT NULL,
  CREATE_TIME DATETIME AS CURRENT_TIMESTAMP,
  MODIFY_TIME DATETIME AS CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (EMP_ID),
  FOREIGN KEY (DPT_ID)
  REFERENCES DEPARTMENT (DPT_ID)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT
);